name: assignment
channels:
  - conda-forge
dependencies:
  # required
  - python=3.8.3
  - numpy=1.19.1
  - matplotlib=3.3.1
  - tqdm=4.60.0
  - pytorch=1.8.0
  - torchvision=0.9.0
  - requests=2.25.1
  
